<?php
$translate = $this->plugin('translate');
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;
?>
<?php echo $this->pageTitle($item->displayTitle(null, $valueLang), 2); ?>
<?php $this->trigger('view.show.before'); ?>

<div class="item-columns">
  <div class="item-column item-column-left">
    <?php echo $this->resourcePageBlocks($item, 'left')->getBlocks(); ?>
  </div>

  <div class="item-column item-column-middle">
    <?php echo $this->resourcePageBlocks($item, 'middle')->getBlocks(); ?>
  </div>

  <div class="item-column item-column-right">
    <?php if ($this->resourcePageBlocks($item, 'right')->hasBlocks()): ?>
      <?php echo $this->resourcePageBlocks($item, 'right')->getBlocks(); ?>
    <?php endif; ?>
  </div>
</div>

<?php $this->trigger('view.show.after'); ?>
